{
  "$schema": "https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json",
  "version": "0.2",
  "dictionaryDefinitions": [
    {
      "name": "project-words",
      "path": ".cspell/project-words.txt",
      "addWords": true
    }
  ],
  "dictionaries": [
    "project-words"
  ],
  "ignorePaths": [
    "node_modules",
    "bin",
    "packages/*/dist",
    "build",
    ".cspell/project-words.txt"
  ],
  "files": [
    "**/*.md",
    "src/**/*.{js,jsx,ts,tsx}",
    "**/*.json"
  ],
  "spellcheckLanguage": "en",
  "enabled": true
}
