# .github/workflows/main.yml
name: Node.js CI and Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  node-ci:
    uses: ./.github/workflows/node-ci.yml  # Correct reference to local reusable workflow
    with:
      node-version: '16.x'
    secrets:
      ACTIONS_DEPLOY_TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}

  deployment:
    needs: node-ci  # This ensures deployment happens only after the Node.js CI job succeeds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set the remote URL with the Personal Access Token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_DEPLOY_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Deploy using gh-pages
        run: |
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
