# .github/workflows/main.yml

name: CI/CD Pipeline for Node.js App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  node-setup:
    uses: ./node.yml  # Calls the node.yml workflow
    with:
      node-version: '16.x'  # Or any version you prefer
      cache-npm: 'true'

  build:
    runs-on: ubuntu-latest
    needs: node-setup  # Ensure node-setup runs first

    steps:
      - uses: actions/checkout@v3
      - run: npm run build --if-present
      - run: npm test

  deploy:
    uses: ./deploy.yml  # Calls the deploy.yml workflow
    with:
      deploy-branch: 'gh-pages'
      deploy-command: 'npm run deploy'
      github-token: ${{ secrets.GITHUB_TOKEN }}
    needs: build  # Ensure build runs before deploy
