name: Spell Check

on:
  workflow_call:
    # This ensures that this reusable workflow doesn't expect secrets, or pass them from the caller.
    # If needed, we can pass `secrets` directly from the calling workflow.

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v3
        name: Spell Check
        id: spellcheck
        continue-on-error: true
        with:
          github_token: ${{ github.token }}  # Use the GitHub token automatically provided by the system
          config: cspell.config.yaml
          inline: warning
          root: '.'
          check_dot_files: false
          strict: true
          incremental_files_only: false
          verbose: false
          files: |
            README.md
            **/*.md
            !dist/**/*.{ts,js}
      - name: 'View results'
        run: |
          echo ${{ steps.spellcheck.outputs.number_of_files_checked }}
          echo ${{ steps.spellcheck.outputs.number_of_files_with_issues }}
          echo ${{ steps.spellcheck.outputs.files_with_issues }}
